Pin the fonttools lib version
Fix the mismatch between Odoo PDF/A converter and newer fonttools.
Odoo convert_to_pdfa() accesses a private attribute on the glyph set:
glyphs = ttfont.getGlyphSet()._hmtx.metrics
Recent fonttools no longer exposes ._hmtx on _TTGlyphSetGlyf
This leads to error:
AttributeError: '_TTGlyphSetGlyf' object has no attribute '_hmtx'.